In [1]:
from transformers import AutoTokenizer, MT5ForQuestionAnswering

# Load the tokenizer and model
tokenizer = AutoTokenizer.from_pretrained("google/mt5-small", model_max_length=128)
model = MT5ForQuestionAnswering.from_pretrained("google/mt5-small")


/home/colin/miniconda3/envs/recsys/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/home/colin/miniconda3/envs/recsys/lib/python3.11/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizer

In [11]:
from transformers import pipeline

pipe = pipeline("question-answering", model="google/mt5-small")

Some weights of MT5ForQuestionAnswering were not initialized from the model checkpoint at google/mt5-small and are newly initialized: ['qa_outputs.bias', 'qa_outputs.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/colin/miniconda3/envs/recsys/lib/python3.11/site-packages/transformers/convert_slow_tokenizer.py:560: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(


In [13]:
question = "Where do I live?"
context = "My name is Merve and I live in İstanbul."
pipe(question = question, context = context)

{'score': 0.12422598898410797, 'start': 0, 'end': 2, 'answer': 'My'}

In [3]:
!pip list | grep transformers

transformers             4.41.2


In [6]:
model.base_model

MT5ForQuestionAnswering(
  (shared): Embedding(250112, 512)
  (encoder): MT5Stack(
    (embed_tokens): Embedding(250112, 512)
    (block): ModuleList(
      (0): MT5Block(
        (layer): ModuleList(
          (0): MT5LayerSelfAttention(
            (SelfAttention): MT5Attention(
              (q): Linear(in_features=512, out_features=384, bias=False)
              (k): Linear(in_features=512, out_features=384, bias=False)
              (v): Linear(in_features=512, out_features=384, bias=False)
              (o): Linear(in_features=384, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 6)
            )
            (layer_norm): MT5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): MT5LayerFF(
            (DenseReluDense): MT5DenseGatedActDense(
              (wi_0): Linear(in_features=512, out_features=1024, bias=False)
              (wi_1): Linear(in_features=512, out_features=1024, bias=False)
              

In [4]:
print(tokenizer("yes"))
print(tokenizer("ja"))
print(tokenizer("nee"))
print(tokenizer("no"))

print(tokenizer("nej"))
print(tokenizer("og"))


{'input_ids': [36339, 1], 'attention_mask': [1, 1]}
{'input_ids': [432, 1], 'attention_mask': [1, 1]}
{'input_ids': [448, 265, 1], 'attention_mask': [1, 1, 1]}
{'input_ids': [375, 1], 'attention_mask': [1, 1]}
{'input_ids': [3810, 1], 'attention_mask': [1, 1]}
{'input_ids': [373, 1], 'attention_mask': [1, 1]}


In [4]:
input_text = ["yes yes yes yes yes yes yes yes yes", "yes yes"]

# Tokenize the input text
inputs = tokenizer(input_text, padding='max_length', max_length=128, truncation=True, return_tensors='pt')
print(inputs.input_ids.shape)


torch.Size([2, 128])


In [10]:
outputs = model.generate(inputs.input_ids)
# 
print(tokenizer.decode(outputs[0], skip_special_tokens=True))


TypeError: The current model class (MT5ForQuestionAnswering) is not compatible with `.generate()`, as it doesn't have a language model head. Please use one of the following classes instead: {'MT5ForConditionalGeneration'}

In [6]:
# Prepare decoder input ids (usually the start token)
decoder_input_ids = tokenizer(["",""], return_tensors="pt").input_ids
print(decoder_input_ids.shape)

# Forward pass with decoder input ids
outputs = model.base_model(input_ids=inputs["input_ids"], decoder_input_ids=decoder_input_ids)

outputs

torch.Size([2, 1])


Seq2SeqQuestionAnsweringModelOutput(loss=None, start_logits=tensor([[-2.3089],
        [-1.7551]], grad_fn=<CloneBackward0>), end_logits=tensor([[0.0381],
        [0.0320]], grad_fn=<CloneBackward0>), past_key_values=((tensor([[[[-9.8412e-01, -3.2376e-01,  1.3064e+00,  5.9792e-01,  2.0006e+00,
           -1.6305e+00,  8.0088e-03,  9.0871e-01,  8.0679e-01,  2.4820e+00,
            6.3779e-02,  2.0918e+00,  9.1891e-02,  6.3571e+00, -2.0570e+00,
           -1.1355e+00, -5.4844e+00, -1.9977e+00, -9.0450e-01, -1.5381e+00,
           -1.4174e+00,  5.5126e-01, -1.3446e+00, -4.1652e-01,  4.4516e-01,
            4.9527e-02, -3.5272e-01,  3.3415e-02, -7.7275e-01, -2.4053e-01,
           -4.3491e-01, -1.8729e-01,  5.0215e-01, -4.3215e-01,  4.7744e-01,
           -5.8970e-02, -1.1967e+00,  1.6951e-01, -5.8363e-01, -9.8546e-01,
            2.8883e-03, -2.8518e-01,  4.5335e-01, -5.6306e-01,  2.6960e-01,
            5.6619e-02,  4.8789e-01, -3.3637e-01,  8.7251e-02, -5.8520e-01,
            4.3483e-0

In [9]:
logits = outputs.logits
print(logits.shape)

AttributeError: 'Seq2SeqQuestionAnsweringModelOutput' object has no attribute 'logits'

In [13]:
print('logit yes', outputs.logits[0,0,36339])
print('logit no',  outputs.logits[0,0,375])

logit yes tensor(-36.5104, grad_fn=<SelectBackward0>)
logit no tensor(-35.1915, grad_fn=<SelectBackward0>)


In [15]:
import torch
def compute_rank_loss(logits_pos, logits_neg):
    r_pos = torch.sigmoid(logits_pos)
    r_neg = torch.sigmoid(logits_neg)
    diff = torch.sigmoid(r_pos - r_neg)
    return torch.log(1e-8 + torch.exp(diff))


In [16]:
from torch.nn import CrossEntropyLoss

ce = CrossEntropyLoss()


In [26]:
positive_string = ["og", "og og"]
negative_string = ["nej", "nej javlar"]


#training step

input_pos = tokenizer(positive_string, padding='max_length', max_length=128, truncation=True, return_tensors='pt')
input_neg = tokenizer(negative_string, padding='max_length', max_length=128, truncation=True, return_tensors='pt')

# print(input_pos)

decoder_input = tokenizer(["",""], return_tensors="pt")

decoder_input_ids

print(decoder_input_ids)

outputs_pos = model.base_model(input_ids=input_pos.input_ids, 
                               attention_mask=input_pos.attention_mask,
                               decoder_input_ids=decoder_input.input_ids,
                               decoder_attention_mask=decoder_input.attention_mask)
outputs_neg = model.base_model(input_ids=input_neg.input_ids, 
                               attention_mask=input_neg.attention_mask,
                               decoder_input_ids=decoder_input.input_ids,
                               decoder_attention_mask=decoder_input.attention_mask)

#logits = [yes,no]
logits_pos = torch.stack((outputs_pos.logits[:,-1,36399], outputs_pos.logits[:,-1,375]), dim=1)
logits_neg = torch.stack((outputs_neg.logits[:,-1,36399], outputs_neg.logits[:,-1,375]), dim=1)

print(logits_pos)

target_pos = torch.tensor([1,0],dtype=torch.float).unsqueeze(0).repeat(logits_pos.shape[0],1)
target_neg = torch.tensor([0,1],dtype=torch.float).unsqueeze(0).repeat(logits_pos.shape[0],1)

loss_nll = ce(logits_pos, target_pos) + ce(logits_neg, target_neg)
loss_bpr = -compute_rank_loss(logits_pos[0], logits_neg[0]).mean(dim=0)

lamb=0.5
loss = (1-lamb)*loss_nll + lamb*loss_bpr

loss.backward()




tensor([[1],
        [1]])
tensor([[-70.1002, -60.0054],
        [-73.3915, -61.9784]], grad_fn=<StackBackward0>)


In [25]:
import torch
def compute_rank_loss_alt(logits_pos, logits_neg):
    r_pos = torch.sigmoid(logits_pos)
    r_neg = torch.sigmoid(logits_neg)
    diff = torch.sigmoid(r_pos - r_neg)
    return torch.log(1e-8 + torch.exp(diff))


In [26]:
batch = [("ja", "nej"),  ("og", "nej javlar")]

pos_inputs = tokenizer([p for p, _ in batch], return_tensors='pt', padding=True, truncation=True)
neg_inputs = tokenizer([n for _, n in batch], return_tensors='pt', padding=True, truncation=True)

with tokenizer.as_target_tokenizer():
    pos_targets = tokenizer(['ja' for _ in batch], return_tensors="pt", padding=True, truncation=True)
    neg_targets = tokenizer(['nej' for _ in batch], return_tensors="pt", padding=True, truncation=True)
    decoder_start = tokenizer(['ja / nej' for _ in batch], return_tensors="pt", padding=True, truncation=True)

batch = {
    "pos_input_ids": pos_inputs["input_ids"],
    "pos_attention_mask": pos_inputs["attention_mask"],
    "neg_input_ids": neg_inputs["input_ids"],
    "neg_attention_mask": neg_inputs["attention_mask"],
    "pos_labels": pos_targets["input_ids"],
    "neg_labels": neg_targets["input_ids"],
    "decoder_start": decoder_start["input_ids"]
}



# Forward pass for the positive and negative examples
pos_outputs = model(
    input_ids=batch["pos_input_ids"], 
    attention_mask=batch["pos_attention_mask"],
    decoder_input_ids=batch["decoder_start"],
)
neg_outputs = model(
    input_ids=batch["neg_input_ids"],
    attention_mask=batch["neg_attention_mask"],
    decoder_input_ids=batch["decoder_start"],
)

# Only take the first token (should be 'ja' or 'nej')
pos_logits = pos_outputs.start_logits
neg_logits = neg_outputs.start_logits

pos_probs = torch.softmax(pos_logits, dim=-1)  # B, V -> B,V
neg_probs = torch.softmax(neg_logits, dim=-1)

print(pos_probs)
pos_target = torch.tensor([0,0])
neg_target = torch.tensor([3,3])
# Compute loss
labda=0.5
loss_nll = ce(pos_logits, pos_target) + ce(neg_logits, neg_target)
pos_prob_yes = pos_probs[0]
neg_prob_yes = neg_probs[0]
loss_bpr = compute_rank_loss(pos_prob_yes, neg_prob_yes).mean(dim=0)
loss = (1-labda)*loss_nll + labda*loss_bpr

print(loss_bpr)

print(loss)

/home/colin/miniconda3/envs/recsys/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:3946: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(


tensor([[0.2178, 0.1689, 0.1572, 0.2163, 0.2397],
        [0.1789, 0.1417, 0.1809, 0.2066, 0.2918]], grad_fn=<SoftmaxBackward0>)
tensor(0.5000, grad_fn=<MeanBackward1>)
tensor(1.8617, grad_fn=<AddBackward0>)
